name: bracket_helper
description: "A new Flutter project."
publish_to: 'none' 

version: 0.250414.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  drift: ^2.26.0
  path: ^1.9.1
  path_provider: ^2.1.5
  get_it: ^8.0.3
  sqlite3_flutter_libs: ^0.5.32
  sqlite3: ^2.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  drift_dev: ^2.26.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
